/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    AConfigProvider: typeof import('ant-design-vue/lib')['ConfigProvider']
    ASpin: typeof import('ant-design-vue/lib')['Spin']
    Center: typeof import('./src/components/center/index.vue')['default']
    Left: typeof import('./src/components/left/index.vue')['default']
    ProNumberInput: typeof import('./src/components/ProNumberInput/index.vue')['default']
    Right: typeof import('./src/components/right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextureEditor: typeof import('./src/components/TextureEditor/index.vue')['default']
  }
}
